name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan your_server_ip >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: ssh ubuntu@your_server_ip "cd /home/ubuntu/flask_app && git pull && sudo systemctl restart flask_app"
